---
- name: Install tcpdump
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install tcpdump
      apt:
        name: tcpdump
        state: present